---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR2RENDQXFTZ0F3SUJBZ0lKQUpiMEJ2ZHZVa09ETUEwR0NTcUdTSWIzRFFFQkN3VUFNRWN4Q3pBSkJnTlYKQkFZVEFrTk9NUXN3Q1FZRFZRUUlEQUpJUWpFTE1Ba0dBMVVFQ2d3Q1VVTXhIakFjQmdOVkJBTU1GV3QxWW1VdApaWFpsYm5SekxXRmtiV2x6YzJsdmJqQWVGdzB5TVRBNE1UWXdPVEkwTkROYUZ3MHpNVEE0TVRRd09USTBORE5hCk1HVXhDekFKQmdOVkJBWVRBa05PTVFzd0NRWURWUVFJREFKSVFqRUxNQWtHQTFVRUNnd0NVVU14UERBNkJnTlYKQkFNTU0ydDFZbVV0WlhabGJuUnpMV0ZrYldsemMybHZiaTVyZFdKbGMzQm9aWEpsTFd4dloyZHBibWN0YzNsegpkR1Z0TG5OMll6Q0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUo0dWZkVC9VSmtCCmQ5L1ArSHRPWkFHUmkrYmZXR0dVR0ZWMHhrOVA2c1ZFSk8xMTAybWVVMDhzcGNTWkZXU0tmRTlIVCswY2E5NkEKMUp3SWZiNkxCMnQ2Wk5mb0lWY01VdG85aEpIYlRXdHRZZE5FU3MwUEIrSktrY1pidy9UN0tnVXA4cDhUVTZKRgp3a2Z0TDRLdVdDSlZpeGkrNnEzVFdYV2dXQjNXaEF0NHdCdUZTK210R2hGamVWWEpwM3NBUGlWVXVJV1poUWVQCnhscS84LzI4ekJNV3poUHNzQ2EydWxTRlV3VytUSEsrTHloMm9PWjM3ZkR5dGpNK1JLMWlNdE4yZkxUc1QwdzkKWllaUFArQU4zZDRyTURtTDRyaG9VTVBJa0NrSjB3c2RZVVpIVnJvREhPUlhSVUlJbDdnNEJHaWpCTVRqbFZSYwoyZkZHaUhlM09HTUNBd0VBQWFPQmpEQ0JpVENCaGdZRFZSMFJCSDh3ZllJVmEzVmlaUzFsZG1WdWRITXRZV1J0CmFYTnphVzl1Z2k5cmRXSmxMV1YyWlc1MGN5MWhaRzFwYzNOcGIyNHVhM1ZpWlhOd2FHVnlaUzFzYjJkbmFXNW4KTFhONWMzUmxiWUl6YTNWaVpTMWxkbVZ1ZEhNdFlXUnRhWE56YVc5dUxtdDFZbVZ6Y0dobGNtVXRiRzluWjJsdQpaeTF6ZVhOMFpXMHVjM1pqTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDZEFuYWFNYUc4Z01XU3gwdm5CdGd5CjFsalhzTUdZdnQ3TnJoT3JacWVtTUVSSkdjUHFVZGpJdks4L1RJVENYa2Rac3BGOGZSZHRUZHFWUnRpSFV4dUUKUGJ6M3Z5ejk5aVZ5OHIvODFPdUxEdUlVZkJuN1laRTBJZVZvMkdtTVFuODhCYXFwSjUvQzNGVXpvOTIxVkJIUAp4RzkvR2gyMjhMOElBamg1cW12R2dCQmJaT1FpaWlBZTJ5TU12Uy9teXNyUExXNndHUjRwLzdoYXlwenRzY0VOCmk1dmlNT1MxVUpvTU4wdGZPQytlc3VQclU5VldYRUIxU2xyZTNkOVc5dWdueCtGK3ZCY1EvNnZ3K3BuR1AwZmQKU3lwZmZZWDRpc1NrWllySU9TcFlZakJQdXVUWkFjemhIRFJtdFNTeHgxRksrczkwTm4rbndqTEZyUU40UisvLwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBbmk1OTFQOVFtUUYzMzgvNGUwNWtBWkdMNXQ5WVlaUVlWWFRHVDAvcXhVUWs3WFhUCmFaNVRUeXlseEprVlpJcDhUMGRQN1J4cjNvRFVuQWg5dm9zSGEzcGsxK2doVnd4UzJqMkVrZHROYTIxaDAwUksKelE4SDRrcVJ4bHZEOVBzcUJTbnlueE5Ub2tYQ1IrMHZncTVZSWxXTEdMN3FyZE5aZGFCWUhkYUVDM2pBRzRWTAo2YTBhRVdONVZjbW5ld0ErSlZTNGhabUZCNC9HV3Ivei9iek1FeGJPRSt5d0pyYTZWSVZUQmI1TWNyNHZLSGFnCjVuZnQ4UEsyTXo1RXJXSXkwM1o4dE94UFREMWxoazgvNEEzZDNpc3dPWXZpdUdoUXc4aVFLUW5UQ3gxaFJrZFcKdWdNYzVGZEZRZ2lYdURnRWFLTUV4T09WVkZ6WjhVYUlkN2M0WXdJREFRQUJBb0lCQVFDVzFRWXZ3SFQrTVNRNQpTbnBLT2VtcWhUcStIMktMU1VnYTFJcjB2ZVBEenNMWG0yN0lXNnhjNXRuNnFXNTR2SVRrbzc5Vy9hN3VNREtMCnhwMEF3Rm1HNXVLWjdrTThXZ2YzQ29vSyt1N0w3VFZHMnV2b3ROaHpzMTlsb2NNdEt3SmFnakZUOW4zZFVsOTcKYm5QTFRLdkZzWVE5U0c5RzZTMTR1RGpOMnV0MmMySDJ0ZlVPR3N1a2ZENEhhK0wxRUpWdVpCeDZ5OFMrMDc3Lwp4RVdHQXl6NU9TK1FvOTBJV2h4ZFNoMncwa0taUTA2aHpkQUVMWjU1blBaWHMyaHA5dzJnMTJQZHNmU1AyQ2IrCk5jTmVpUFdneC8wSVJadkVjcmtUTkpKampCZmNMK1VxYzdDVVU0b2pNcnBuOHZTR3pzdEMzZjVRTU1TdXdyK2UKNnBscExIVEJBb0dCQU01bzhtNG1wMmJvYUx6QjY3MDd5QWNGeFl5cDNLZzY2elJGMDljd255TlplSkpmdlBiQQozS3Vyc2xaQ1AwUEZYZEhuSWVMU09oVi95UEdMRmsxcnJLSjR2Qnl1WXdZZzRhT2tJZFo4RjJNRWRIQVJuZGs1Cm9iSksyRjJmMVpsWGt2TEpjaGFWaTRKeHdONFU2bWxVd1NZYmFOV1ZmeHFoVEtWVmZMcmcwY0tKQW9HQkFNUXYKVGhRUXFRTk9zMkdhZG0xVTh3NUc1VjNuN1pCWS9ONHFGR3JCeGhpTy9TLzY5ZGQzS0xVbENYbXQ0aGNaVml3cwpuZjlOME0wd0hOYjVTdnVDN1pieEtpUkxNL1JFQUF5VCt0WjBndXlwUU9rbkpod3pJSjhpNTQ0dTB4TWNaWG16CjFtOHYxcks0ZUgzb3YrQ1VncjFrUHA2L3hpK2V5OGltYmg4Y2Q5aUxBb0dBTnBQM2JucllEdFRyUk9YOTRJYWIKS0lnMUtUR05BQXE4UUpFcUo1OWFwTzAyZlhYRk1IWGtvNXY5eHVNemVVY0p2TVBoNk9qdnBObXFGM3hRaEY0eApRckNzQk9Wemw1NUFLNVh0d0pvRlVSQlBmWWFhOTJKT3lDY1VPUVZYWkhtTWlKZ05pNzAxSzJQS3ZLNUpJVnJnCnk2TzV2NmdNK015bnlKdm5KRDdvR0FrQ2dZRUF1V1Z1NXIxYnl6bGJnWmhENUV4TUtTak1adkxmYVBML2ZEL04KN1psVFNEQVFpb0FpUlUxaFZkWTdYeGI0dXhXQmZ0dG5NRFpzWlF2YnBUZ1BLU0h3dngwRzB5ZVNZSHJHaFJ4dgpCcTB5Y00zOS9wZTFoeDYxN0UxQy8vVzJHTEJVSVMvWExGbk1EamNQL3dTdUYyQ2hNTE9FRGVkek5kdGQveTl3Cmo4d0tZY01DZ1lBanEzSWJKZEM4TjRPM25EUkt3Z0pMcnRBdnhoTVExZjBMYjFFRFphejFlWXhCcUUyOHk0NlAKQWJzcVhma00xaUhPOG1XMU1xLzdVL0s0di9pNW9WQ2wvbzl5M3lwNmtPeXNOZU5KWkFFS1oySGh5WmNmQzdXYwpYKzluWlBmaSt0ZVE2TWplMUF3VTNHdnRFekNGSmVkVCtaSmpsQUpnMDU5UTU2aUxsMmVRTnc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  name: admission
  namespace: system
type: Opaque
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: admission-mutate
webhooks:
- admissionReviewVersions:
    - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURiekNDQWxlZ0F3SUJBZ0lVSkIzTFlLZ0RyamwxSlhwb3ZyRXR2TTRPZjRBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1J6RUxNQWtHQTFVRUJoTUNRMDR4Q3pBSkJnTlZCQWdNQWtoQ01Rc3dDUVlEVlFRS0RBSlJRekVlTUJ3RwpBMVVFQXd3VmEzVmlaUzFsZG1WdWRITXRZV1J0YVhOemFXOXVNQjRYRFRJeE1EZ3hOakE1TWpRME0xb1hEVE14Ck1EZ3hOREE1TWpRME0xb3dSekVMTUFrR0ExVUVCaE1DUTA0eEN6QUpCZ05WQkFnTUFraENNUXN3Q1FZRFZRUUsKREFKUlF6RWVNQndHQTFVRUF3d1ZhM1ZpWlMxbGRtVnVkSE10WVdSdGFYTnphVzl1TUlJQklqQU5CZ2txaGtpRwo5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMkN5cjZDSS8vN1RsbHFqcjJhV0ZBd1FiRGVlb1I3TUt0VHR0CmMxVGlDWXBLNVNKZ0d6Q25relI4NS9rWTk2cC9WTTIrRHU2S2JTb24yQW82dU9pc05kT285ck5LMUxCVUxBUm0KRmtWdnVnRm9hRXY0Ykg2U3VmelFHaWpRRlQ3b3VVUkc0MDVhSWNzY2ljYkRISTJRWUFVY2JaOS9ZZmpiWVVuegpDdkYwMTBDcFlEZGk5Mk12SDBielA5d3F3UUJYdjhBYzlGOTROL0VQWXlINVRMcHE4cEtLU0wzbXF5eHkyRkFsCjZBbHJ2Yjl0Tm01cGpkOHo4VmptdVNHckZmbGFKS2xKUXBaSXJjYUU1d2hDbzFYMVR0WFZROFpKTGYzTzlremwKUjVuRGZOQVZzQllwS2R2VmFrMFpkai9aYmtTdlhRTVBtcFlGRjdqenZVUy91Ny84MHdJREFRQUJvMU13VVRBZApCZ05WSFE0RUZnUVVoTzU5NHMzakErTVZCNStXeWZjczZ6czBha1F3SHdZRFZSMGpCQmd3Rm9BVWhPNTk0czNqCkErTVZCNStXeWZjczZ6czBha1F3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCQVFzRkFBT0MKQVFFQVVMbXNNbVZXdzg3QUhXU3g5eU5mMWswVXRFc3kvczE5YjRuSGxUazN0QXhNQVBQT29kNVg0dnk5SkFhagpQcnBwNHJoSHduWUVYVXozNEN1ekhveTcxTGIxck5CTTVrcFl0QXFaWkRTaVB2aVd2TnJES2E4TVQxNERIL2MvCklOK1BMbGJsb09kVko3bVdpdTNGVFk1ZndMZldmWktPbFZYOUpuWFhReEludHJWWnZpbDhLUDVsY29nWnQrRmoKZ3FkZ3hhOUhiL3Z5MkZqbjZNUElubjYzdXlhRmtkZzVteTZ3QllGUVo0b1grcUVOdTRMNE81bGpxSlVNTlcwawpJRFNueE05ZUxPMzRuMHBkaWtmaCtlV3ROSWlMdTRWNVpYK0h2cTYyR21xWnRobjBJV0tIajlzOXhQMkJNT01BCm9rN29hb0RoZ0hEM0k5M2xjVm5vUUZrNE1BPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: $(ADMISSION_SERVICE_NAME)
      namespace: $(ADMISSION_SERVICE_NAMESPACE)
      path: /mutate-events-kubesphere-io-v1alpha1-rule
  failurePolicy: Fail
  name: mrule.kb.io
  rules:
  - apiGroups:
    - events.kubesphere.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rules
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: admission-validate
webhooks:
- admissionReviewVersions:
    - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURiekNDQWxlZ0F3SUJBZ0lVSkIzTFlLZ0RyamwxSlhwb3ZyRXR2TTRPZjRBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1J6RUxNQWtHQTFVRUJoTUNRMDR4Q3pBSkJnTlZCQWdNQWtoQ01Rc3dDUVlEVlFRS0RBSlJRekVlTUJ3RwpBMVVFQXd3VmEzVmlaUzFsZG1WdWRITXRZV1J0YVhOemFXOXVNQjRYRFRJeE1EZ3hOakE1TWpRME0xb1hEVE14Ck1EZ3hOREE1TWpRME0xb3dSekVMTUFrR0ExVUVCaE1DUTA0eEN6QUpCZ05WQkFnTUFraENNUXN3Q1FZRFZRUUsKREFKUlF6RWVNQndHQTFVRUF3d1ZhM1ZpWlMxbGRtVnVkSE10WVdSdGFYTnphVzl1TUlJQklqQU5CZ2txaGtpRwo5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMkN5cjZDSS8vN1RsbHFqcjJhV0ZBd1FiRGVlb1I3TUt0VHR0CmMxVGlDWXBLNVNKZ0d6Q25relI4NS9rWTk2cC9WTTIrRHU2S2JTb24yQW82dU9pc05kT285ck5LMUxCVUxBUm0KRmtWdnVnRm9hRXY0Ykg2U3VmelFHaWpRRlQ3b3VVUkc0MDVhSWNzY2ljYkRISTJRWUFVY2JaOS9ZZmpiWVVuegpDdkYwMTBDcFlEZGk5Mk12SDBielA5d3F3UUJYdjhBYzlGOTROL0VQWXlINVRMcHE4cEtLU0wzbXF5eHkyRkFsCjZBbHJ2Yjl0Tm01cGpkOHo4VmptdVNHckZmbGFKS2xKUXBaSXJjYUU1d2hDbzFYMVR0WFZROFpKTGYzTzlremwKUjVuRGZOQVZzQllwS2R2VmFrMFpkai9aYmtTdlhRTVBtcFlGRjdqenZVUy91Ny84MHdJREFRQUJvMU13VVRBZApCZ05WSFE0RUZnUVVoTzU5NHMzakErTVZCNStXeWZjczZ6czBha1F3SHdZRFZSMGpCQmd3Rm9BVWhPNTk0czNqCkErTVZCNStXeWZjczZ6czBha1F3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCQVFzRkFBT0MKQVFFQVVMbXNNbVZXdzg3QUhXU3g5eU5mMWswVXRFc3kvczE5YjRuSGxUazN0QXhNQVBQT29kNVg0dnk5SkFhagpQcnBwNHJoSHduWUVYVXozNEN1ekhveTcxTGIxck5CTTVrcFl0QXFaWkRTaVB2aVd2TnJES2E4TVQxNERIL2MvCklOK1BMbGJsb09kVko3bVdpdTNGVFk1ZndMZldmWktPbFZYOUpuWFhReEludHJWWnZpbDhLUDVsY29nWnQrRmoKZ3FkZ3hhOUhiL3Z5MkZqbjZNUElubjYzdXlhRmtkZzVteTZ3QllGUVo0b1grcUVOdTRMNE81bGpxSlVNTlcwawpJRFNueE05ZUxPMzRuMHBkaWtmaCtlV3ROSWlMdTRWNVpYK0h2cTYyR21xWnRobjBJV0tIajlzOXhQMkJNT01BCm9rN29hb0RoZ0hEM0k5M2xjVm5vUUZrNE1BPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: $(ADMISSION_SERVICE_NAME)
      namespace: $(ADMISSION_SERVICE_NAMESPACE)
      path: /validate-events-kubesphere-io-v1alpha1-rule
  failurePolicy: Fail
  name: vrule.kb.io
  rules:
  - apiGroups:
    - events.kubesphere.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rules
  sideEffects: None
---
apiVersion: v1
kind: Service
metadata:
  name: admission
  namespace: system
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    app: $(OPERATOR_NAME)