---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $(OPERATOR_NAME)
  template:
    metadata:
      labels:
        app: $(OPERATOR_NAME)
    spec:
      serviceAccountName: operator
      containers:
      - image: operator
        name: events-operator
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
          - containerPort: 9443
            name: webhook-server
            protocol: TCP
        volumeMounts:
          - mountPath: /tmp/k8s-webhook-server/serving-certs
            name: cert
            readOnly: true
      volumes:
        - name: cert
          secret:
            secretName: admission