
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURaakNDQWs2Z0F3SUJBZ0lKQUpMM3VIb3duRXpHTUEwR0NTcUdTSWIzRFFFQkN3VUFNRWd4Q3pBSkJnTlYKQkFZVEFrTk9NUXN3Q1FZRFZRUUlEQUpJUWpFTE1Ba0dBMVVFQ2d3Q1VVTXhIekFkQmdOVkJBTU1GbVYyWlc1MApjeTEzWldKb2IyOXJMWE5sY25acFkyVXdIaGNOTWpBd016STNNRGd3TnpJMFdoY05ORGN3T0RFek1EZ3dOekkwCldqQklNUXN3Q1FZRFZRUUdFd0pEVGpFTE1Ba0dBMVVFQ0F3Q1NFSXhDekFKQmdOVkJBb01BbEZETVI4d0hRWUQKVlFRRERCWmxkbVZ1ZEhNdGQyVmlhRzl2YXkxelpYSjJhV05sTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQwpBUThBTUlJQkNnS0NBUUVBNnE0bVpidTcyZjMzMFkwZXJWUzROR1FPVURPamNDQ0RzcExRWitjRkZNYjd1c04xCmtSaHdkd2NJeE9RZkFtMFNkUzhRTkk5T0hzNld4UTF4RXJRUjlUcUk1TmgvZnhjdzh2NnJaLy9lQ0htSFNwSzgKcllaVU5OSEJIUmhwUE03NVVrU1RkYXBISVlYU1d0NCtQcDBKMXNnT2RLNDJKZThwOGIyMWRPUi9OM1I0NTExVAp1Y3dCUHR3OHRmM2xYZFV4QkVuZFJoWmV2TitJWDlWTDdzU3BOVXROOU50MmcyU2prY3VZVHJLWHNyU09XOTg4Cm1zOHM2VDJ1MkNZd1c1REJIYVUveXEraDNDLzBnWmprNEJuVUJWUHh2WlFNSTlpK3hDNU9lVFZCUmhyRjJXS1kKclliKzF0YXE1WWIva0RPMERBanI1S3owMmltTzlsSGxTenhTd1FJREFRQUJvMU13VVRBZEJnTlZIUTRFRmdRVQpFZ21TREpLZGxodjhESTJJWkJETkEyZ1I5Zll3SHdZRFZSMGpCQmd3Rm9BVUVnbVNESktkbGh2OERJMklaQkROCkEyZ1I5Zll3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBYmdoMENabkoKcmlKSlZnT1VWOWJ6WW44cEh2M3ExVnVqRThBUU9wRHBidDdmaTlaOE1UVnRTTGtOVFlaQmo4c1RLTklkaVBxMgpUelhKcVNGNTZFUzB1TlNGZmowRU5GVXEvNG9BK29WaVk1cXR1WVZaSVFUQnJrdld4dXg3ZXVybGd6SkFrdWhDCjBpU0NtQ0FvaGp3TTNHc0xMTGxKZjY4WFlNWit3TDhLc1hKb3ZML3h3VGd2bTNxTHlUbDZ0MVpTODRjVzFtZnMKVUR3RWdxTlVNUTFKWWIxV1pzTE1ydjdESktvaGdxcGtzODRuT0drSzV3dnVMQVdjOUUyWXQ4MDJnclVhTFRrcwpaY2w0Y2dMZEhaZWF5UEk5WlRxdGxBNCtDM1dtY1JFb2hIaFZNTUFDZ1pwY0xzeWF2b1hCSmFNL1hpRFpLTXEyCkc3cHp6RmpWTmNWNGZnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: webhook-service
      namespace: system
      path: /mutate-logging-kubesphere-io-v1alpha1-kubeeventsrule
  failurePolicy: Fail
  name: mkubeeventsrule.kb.io
  rules:
  - apiGroups:
    - logging.kubesphere.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kubeeventsrules

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURaakNDQWs2Z0F3SUJBZ0lKQUpMM3VIb3duRXpHTUEwR0NTcUdTSWIzRFFFQkN3VUFNRWd4Q3pBSkJnTlYKQkFZVEFrTk9NUXN3Q1FZRFZRUUlEQUpJUWpFTE1Ba0dBMVVFQ2d3Q1VVTXhIekFkQmdOVkJBTU1GbVYyWlc1MApjeTEzWldKb2IyOXJMWE5sY25acFkyVXdIaGNOTWpBd016STNNRGd3TnpJMFdoY05ORGN3T0RFek1EZ3dOekkwCldqQklNUXN3Q1FZRFZRUUdFd0pEVGpFTE1Ba0dBMVVFQ0F3Q1NFSXhDekFKQmdOVkJBb01BbEZETVI4d0hRWUQKVlFRRERCWmxkbVZ1ZEhNdGQyVmlhRzl2YXkxelpYSjJhV05sTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQwpBUThBTUlJQkNnS0NBUUVBNnE0bVpidTcyZjMzMFkwZXJWUzROR1FPVURPamNDQ0RzcExRWitjRkZNYjd1c04xCmtSaHdkd2NJeE9RZkFtMFNkUzhRTkk5T0hzNld4UTF4RXJRUjlUcUk1TmgvZnhjdzh2NnJaLy9lQ0htSFNwSzgKcllaVU5OSEJIUmhwUE03NVVrU1RkYXBISVlYU1d0NCtQcDBKMXNnT2RLNDJKZThwOGIyMWRPUi9OM1I0NTExVAp1Y3dCUHR3OHRmM2xYZFV4QkVuZFJoWmV2TitJWDlWTDdzU3BOVXROOU50MmcyU2prY3VZVHJLWHNyU09XOTg4Cm1zOHM2VDJ1MkNZd1c1REJIYVUveXEraDNDLzBnWmprNEJuVUJWUHh2WlFNSTlpK3hDNU9lVFZCUmhyRjJXS1kKclliKzF0YXE1WWIva0RPMERBanI1S3owMmltTzlsSGxTenhTd1FJREFRQUJvMU13VVRBZEJnTlZIUTRFRmdRVQpFZ21TREpLZGxodjhESTJJWkJETkEyZ1I5Zll3SHdZRFZSMGpCQmd3Rm9BVUVnbVNESktkbGh2OERJMklaQkROCkEyZ1I5Zll3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBYmdoMENabkoKcmlKSlZnT1VWOWJ6WW44cEh2M3ExVnVqRThBUU9wRHBidDdmaTlaOE1UVnRTTGtOVFlaQmo4c1RLTklkaVBxMgpUelhKcVNGNTZFUzB1TlNGZmowRU5GVXEvNG9BK29WaVk1cXR1WVZaSVFUQnJrdld4dXg3ZXVybGd6SkFrdWhDCjBpU0NtQ0FvaGp3TTNHc0xMTGxKZjY4WFlNWit3TDhLc1hKb3ZML3h3VGd2bTNxTHlUbDZ0MVpTODRjVzFtZnMKVUR3RWdxTlVNUTFKWWIxV1pzTE1ydjdESktvaGdxcGtzODRuT0drSzV3dnVMQVdjOUUyWXQ4MDJnclVhTFRrcwpaY2w0Y2dMZEhaZWF5UEk5WlRxdGxBNCtDM1dtY1JFb2hIaFZNTUFDZ1pwY0xzeWF2b1hCSmFNL1hpRFpLTXEyCkc3cHp6RmpWTmNWNGZnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: webhook-service
      namespace: system
      path: /validate-logging-kubesphere-io-v1alpha1-kubeeventsrule
  failurePolicy: Fail
  name: vkubeeventsrule.kb.io
  rules:
  - apiGroups:
    - logging.kubesphere.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kubeeventsrules
