
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURaakNDQWs2Z0F3SUJBZ0lKQUk1M001WlBzeUZkTUEwR0NTcUdTSWIzRFFFQkN3VUFNRWd4Q3pBSkJnTlYKQkFZVEFrTk9NUXN3Q1FZRFZRUUlEQUpJUWpFTE1Ba0dBMVVFQ2d3Q1VVTXhIekFkQmdOVkJBTU1GbVYyWlc1MApjeTEzWldKb2IyOXJMWE5sY25acFkyVXdIaGNOTWpBd05EQXpNRGt5TVRVeFdoY05ORGN3T0RJd01Ea3lNVFV4CldqQklNUXN3Q1FZRFZRUUdFd0pEVGpFTE1Ba0dBMVVFQ0F3Q1NFSXhDekFKQmdOVkJBb01BbEZETVI4d0hRWUQKVlFRRERCWmxkbVZ1ZEhNdGQyVmlhRzl2YXkxelpYSjJhV05sTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQwpBUThBTUlJQkNnS0NBUUVBemlqRUdzQVpHeFNVRGpJdlNJSE5kSVVwU04vVkxUbmJvS2tYZzYwVkZHYjNtZyttCjdCT2ozNGlhM1BTU0t4aHZOZWY2WVNHdzBUTjRVcng3bnpwSzNocXdpRllVNmhMTTVmOUV1ejhDOWdIdHI2dUMKcGpzbmFmUXM1MWhORmhxc3YvdkxseG9GUmliT2JBblpDQllCaHhDMVM5aGZ6YTAyTXBzdGJIYVRDeHVLT1gzQwp5UDdCaEdwbDUxZGpVMHNSS0xBN3A0S2lsVzNQSHFhbldNcHU1Ykd0UmYyWVFwSlEwcWpuYkw3NnlvNGYrZ2hGCjZJU1ZwTWlrUTdCK3FKREhNL3Z5aVhYZDd6cGgrOUQwUzhDS0wrUk0yd1NyMWZ0SmcxZlFIdjVzR09yTy96WmkKM1ZqNjdBeG9oaFkyb2VKL3h4emxjUHpYU28vVXprQ25aVkl2UlFJREFRQUJvMU13VVRBZEJnTlZIUTRFRmdRVQpIYXlSbENLQUx3bUltUlA0V3JEbnR2ZEFFRll3SHdZRFZSMGpCQmd3Rm9BVUhheVJsQ0tBTHdtSW1SUDRXckRuCnR2ZEFFRll3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBZlNzYzNNWWcKM0VUZkdoUld4dmVjVG9URzVtQllhNkYwbXJ1cHlBeXJTRmlXVS9yclZsclhxZmxIRkY3b0Uvcjl2ZlNJRmFacQpFLytCK01NdWlXMlhQeU4wYllqWjl6UldJYnVsbzJjaDUrZ1lmbkRqWkppZXA5eDVBcEJYS2tRWEJ6aHpKRm8xCmxkSkp1TXhVL2lWenlaekpNZHlRV09zd296a0NNdlNNQzlHZDkvcEVSMmw5c2FYQU9kcjk1RGhDMW1oU1RVb3oKcUZHMnViNlFXb3FmVWdnWUx4ZUkvRlhqWWZrWXYzblhQZm9EUWY5YUdXZS95RDJLaUJKMUhQSjJTL1kyWm1vcgovS0J0RVkyMEVtUWFXUEYzRWlCaEw3eDB4VVhhdjFuQldtSXRPc1dXV1grNUdCa2xhRkxBb1VocWc4OVFucmd5CjMwWGh6SklRS0daTWFRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: webhook-service
      namespace: system
      path: /mutate-logging-kubesphere-io-v1alpha1-kubeeventsrule
  failurePolicy: Fail
  name: mkubeeventsrule.kb.io
  rules:
  - apiGroups:
    - logging.kubesphere.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kubeeventsrules

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURaakNDQWs2Z0F3SUJBZ0lKQUk1M001WlBzeUZkTUEwR0NTcUdTSWIzRFFFQkN3VUFNRWd4Q3pBSkJnTlYKQkFZVEFrTk9NUXN3Q1FZRFZRUUlEQUpJUWpFTE1Ba0dBMVVFQ2d3Q1VVTXhIekFkQmdOVkJBTU1GbVYyWlc1MApjeTEzWldKb2IyOXJMWE5sY25acFkyVXdIaGNOTWpBd05EQXpNRGt5TVRVeFdoY05ORGN3T0RJd01Ea3lNVFV4CldqQklNUXN3Q1FZRFZRUUdFd0pEVGpFTE1Ba0dBMVVFQ0F3Q1NFSXhDekFKQmdOVkJBb01BbEZETVI4d0hRWUQKVlFRRERCWmxkbVZ1ZEhNdGQyVmlhRzl2YXkxelpYSjJhV05sTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQwpBUThBTUlJQkNnS0NBUUVBemlqRUdzQVpHeFNVRGpJdlNJSE5kSVVwU04vVkxUbmJvS2tYZzYwVkZHYjNtZyttCjdCT2ozNGlhM1BTU0t4aHZOZWY2WVNHdzBUTjRVcng3bnpwSzNocXdpRllVNmhMTTVmOUV1ejhDOWdIdHI2dUMKcGpzbmFmUXM1MWhORmhxc3YvdkxseG9GUmliT2JBblpDQllCaHhDMVM5aGZ6YTAyTXBzdGJIYVRDeHVLT1gzQwp5UDdCaEdwbDUxZGpVMHNSS0xBN3A0S2lsVzNQSHFhbldNcHU1Ykd0UmYyWVFwSlEwcWpuYkw3NnlvNGYrZ2hGCjZJU1ZwTWlrUTdCK3FKREhNL3Z5aVhYZDd6cGgrOUQwUzhDS0wrUk0yd1NyMWZ0SmcxZlFIdjVzR09yTy96WmkKM1ZqNjdBeG9oaFkyb2VKL3h4emxjUHpYU28vVXprQ25aVkl2UlFJREFRQUJvMU13VVRBZEJnTlZIUTRFRmdRVQpIYXlSbENLQUx3bUltUlA0V3JEbnR2ZEFFRll3SHdZRFZSMGpCQmd3Rm9BVUhheVJsQ0tBTHdtSW1SUDRXckRuCnR2ZEFFRll3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBZlNzYzNNWWcKM0VUZkdoUld4dmVjVG9URzVtQllhNkYwbXJ1cHlBeXJTRmlXVS9yclZsclhxZmxIRkY3b0Uvcjl2ZlNJRmFacQpFLytCK01NdWlXMlhQeU4wYllqWjl6UldJYnVsbzJjaDUrZ1lmbkRqWkppZXA5eDVBcEJYS2tRWEJ6aHpKRm8xCmxkSkp1TXhVL2lWenlaekpNZHlRV09zd296a0NNdlNNQzlHZDkvcEVSMmw5c2FYQU9kcjk1RGhDMW1oU1RVb3oKcUZHMnViNlFXb3FmVWdnWUx4ZUkvRlhqWWZrWXYzblhQZm9EUWY5YUdXZS95RDJLaUJKMUhQSjJTL1kyWm1vcgovS0J0RVkyMEVtUWFXUEYzRWlCaEw3eDB4VVhhdjFuQldtSXRPc1dXV1grNUdCa2xhRkxBb1VocWc4OVFucmd5CjMwWGh6SklRS0daTWFRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: webhook-service
      namespace: system
      path: /validate-logging-kubesphere-io-v1alpha1-kubeeventsrule
  failurePolicy: Fail
  name: vkubeeventsrule.kb.io
  rules:
  - apiGroups:
    - logging.kubesphere.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kubeeventsrules
