# permissions for end users to edit kubeeventsrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeeventsrule-editor-role
rules:
- apiGroups:
  - logging.kubesphere.io
  resources:
  - kubeeventsrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging.kubesphere.io
  resources:
  - kubeeventsrules/status
  verbs:
  - get
