# permissions for end users to view kubeeventsrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeeventsrule-viewer-role
rules:
- apiGroups:
  - logging.kubesphere.io
  resources:
  - kubeeventsrules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - logging.kubesphere.io
  resources:
  - kubeeventsrules/status
  verbs:
  - get
