# permissions for end users to view kubeeventsexporters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeeventsexporter-viewer-role
rules:
- apiGroups:
  - logging.kubesphere.io
  resources:
  - kubeeventsexporters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - logging.kubesphere.io
  resources:
  - kubeeventsexporters/status
  verbs:
  - get
