# permissions for end users to view kubeeventsrulers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeeventsruler-viewer-role
rules:
- apiGroups:
  - logging.kubesphere.io
  resources:
  - kubeeventsrulers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - logging.kubesphere.io
  resources:
  - kubeeventsrulers/status
  verbs:
  - get
