apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: events-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: events-operator
subjects:
- kind: ServiceAccount
  name: events-operator
  namespace: kubesphere-logging-system
