namespace:
- path: spec/sinks/webhooks/service/namespace
  kind: KubeEventsExporter

namePrefix:
- path: spec/sinks/webhooks/service/name
  kind: KubeEventsExporter

varReference:
- path: webhooks/clientConfig/service
  kind: MutatingWebhookConfiguration
- path: webhooks/clientConfig/service
  kind: ValidatingWebhookConfiguration
- path: spec/template/metadata/labels
  kind: Deployment
- path: spec/selector/matchLabels
  kind: Deployment
- path: spec/selector
  kind: Service

images:
- path: spec/image
  kind: KubeEventsExporter
- path: spec/image
  kind: KubeEventsRuler
