namespace: kubesphere-logging-system
namePrefix: kube-events-

resources:
- crd
- cr
- rbac
- operator

configurations:
- kustomizeconfig.yaml

patchesStrategicMerge:
- ruler_patch.yaml

images:
- name: exporter
  newName: kubespheredev/kube-events-exporter
  newTag: v0.1.0
- name: operator
  newName: kubespheredev/kube-events-operator
  newTag: v0.1.0
- name: ruler
  newName: kubespheredev/kube-events-ruler
  newTag: v0.1.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
