{{- if .Values.operator.enabled }}
{{- $cn := printf "%s.%s.svc" ( include "kube-events.admission.fullname" . ) .Release.Namespace }}
{{- $ca := genCA "kube-events-admission-ca" 3650 -}}
{{- $cert := genSignedCert $cn nil nil 3650 $ca -}}
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ template "kube-events.admission.fullname" . }}-validate
  labels:
{{ include "kube-events.labels" . | indent 4 }}
webhooks:
  - clientConfig:
      caBundle: {{ b64enc $ca.Cert }}
      service:
        name: {{ template "kube-events.admission.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-logging-kubesphere-io-v1alpha1-kubeeventsrule
    failurePolicy: Fail
    name: vkubeeventsrule.kb.io
    rules:
      - apiGroups:
          - logging.kubesphere.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - kubeeventsrules
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "kube-events.admission.fullname" . }}-mutate
  labels:
{{ include "kube-events.labels" . | indent 4 }}
webhooks:
  - clientConfig:
      caBundle: {{ b64enc $ca.Cert }}
      service:
        name: {{ template "kube-events.admission.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate-logging-kubesphere-io-v1alpha1-kubeeventsrule
    failurePolicy: Fail
    name: mkubeeventsrule.kb.io
    rules:
      - apiGroups:
          - logging.kubesphere.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - kubeeventsrules
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kube-events.admission.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kube-events.labels" . | indent 4 }}
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    app: {{ template "kube-events.operator.fullname" . }}
{{ include "kube-events.labels" . | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kube-events.admission.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kube-events.labels" . | indent 4 }}
type: Opaque
data:
  tls.crt: {{ b64enc $cert.Cert }}
  tls.key: {{ b64enc $cert.Key }}
{{- end }}