operator:
  enabled: true
  # just clean up cr but not crd
  cleanupCustomResources: true
  image:
    repository: kubespheredev/kube-events-operator
    tag: v0.1.0
    pullPolicy: IfNotPresent
  configReloader:
    image: jimmidyson/configmap-reload:v0.3.0
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 20m
      memory: 20Mi
  serviceAccount:
    create: true
    name: ""

exporter:
  enabled: true
  image:
    repository: kubespheredev/kube-events-exporter
    tag: v0.1.0
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 20m
      memory: 50Mi
  sinks:
    stdout:
      enabled: true
    additionalWebhooks: []
    # - url:
    #   service:
    #     namespace:
    #     name:
    #     port:
    #     path:

ruler:
  enabled: true
  image:
    repository: kubespheredev/kube-events-ruler
    tag: v0.1.0
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 50m
      memory: 50Mi
  ruleNamespaceSelector: {}
  ruleSelector: {}
  sinks:
    alertmanager:
      namespace: kubesphere-monitoring-system
      name: alertmanager-main
    webhooks: []
    # - type:
    #   url:
    #   service:
    #     namespace:
    #     name:
    #     port:
    #     path:

defaultRules:
  create: true