apiVersion: logging.kubesphere.io/v1alpha1
kind: KubeEventsRuler
metadata:
  name: ruler
  namespace: system
spec:
  image: ruler
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 50m
      memory: 50Mi
  sinks:
    alertmanager:
      namespace: kubesphere-monitoring-system
      name: alertmanager-main